// src/lib/duerpInrsData.js
// Données de référence INRS - 65 risques professionnels avec mapping secteur
// Source: INRS (Institut National de Recherche et de Sécurité)

export const INRS_RISKS = [
  { risque: 'Activité physique', situations: 'Déplacement, transporter soulever, bouger, tirer-pousser, actionner', consequences: 'addiction', reglementation: 'l’article L. 4121-1 du Code du travail impose à l’employeur de prendre les mesures nécessaires pour assurer la sécurité et protéger la santé physique et mentale des travailleurs. Ces mesures comprennent, entre autres, des actions de prévention des risques professionnels et de la pénibilité', source: 'https://www.inrs.fr/risques/activite-physique/ce-qu-il-faut-retenir.html', sectors: ["btp", "transport", "commerce", "industrie", "restauration", "sante", "agriculture", "logistique"] },
  { risque: 'Addiction', situations: 'Consommation de substances psychoactives :  tabac, alcool, médicaments, cannabis, cocaïne, ectasy, héroïne, drogue de synthèse,…', consequences: 'Asthme, anxiété, diminution de la vigilance, maladie du foie, somnolence, troubles de la mémoire, maux de tête, cancers,…', reglementation: 'L’obligation générale de sécurité qui incombe à l\'employeur, définie par la jurisprudence comme une obligation de sécurité de résultat, doit le conduire à prendre toutes les mesures nécessaires pour assurer la sécurité et protéger la santé des travailleurs (article L. 4121-1 du Code du travail 58) L', source: 'https://www.inrs.fr/risques/addictions/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Agression et violence externe', situations: 'Travailler en contact avec le public (physique ou par téléphone) : Incivilités, menaces, agressions verbales ou physiques, cambriolages…', consequences: 'Atteintes physiques à la suite d\'une agression physique (lésions ou blessures) Atteinte psychiques en cas d\'agression physique ou verbale (épercussions psychlogiques : stress aigu, chronique, stresse', reglementation: 'La réglementation sur les violences externes s’appuie sur l’obligation générale de sécurité qui incombe à l’employeur (article L. 4121-1 et suivants du Code du travail) d’évaluer les risques et de prendre les mesures nécessaires pour assurer et protéger la santé physique et mentale ainsi que la sécu', source: 'https://www.inrs.fr/risques/agressions-violences-externes/ce-qu-il-faut-retenir.html', sectors: ["commerce", "sante", "transport", "restauration", "accueil"] },
  { risque: 'Agent sensibilisants', situations: 'L’exposition à des agents sensibilisants en milieu professionnel', consequences: 'Allergies professionnelles, cutanées ou respiratoires (dermatites de contact, l\'asthme professionnel)', reglementation: 'En fonction de la nature de l’agent sensibilisant, la réglementation relative à la prévention du risque chimique 54 et du risque biologique 55 s’applique. Seules quelques spécificités liées au risque de sensibilisation seront abordées ici.', source: 'https://www.inrs.fr/risques/agents-sensibilisants/ce-qu-il-faut-retenir.html', sectors: ["industrie", "chimie", "sante", "agriculture"] },
  { risque: 'Amiante', situations: 'Les travaux de désamiantage et toute intervention de type maintenance ou entretien sur des matériaux en place contenant de l’amiante, y compris sur des installations, équipements, matériels roulants ou flottants, aéronefs ou sur terrains amianti', consequences: 'Mécanisme toxilogique, Atteinte pleurale, Asbestose,Cancers,', reglementation: 'L’obligation générale de formation à la sécurité prévue par le Code du travail (article L. 4141-2), l’employeur doit assurer une formation adaptée aux activités et aux procédés mis en œuvre à tous les salariés susceptibles d’intervenir sur des matériaux amiantés, et ce préalablement à leur première', source: 'https://www.inrs.fr/risques/amiante/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie"] },
  { risque: 'Bien être au travail', situations: 'Le bien-être met l’accent sur la perception personnelle et collective des situations et des contraintes de la sphère professionnelle.', consequences: 'physiques, psychologiques, émotionnelles et psychosociales', reglementation: '', source: 'https://www.inrs.fr/risques/bien-etre-travail/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Risques Biologiques', situations: 'Contact avec avec des agents biologiques', consequences: 'infections, intoxications, allergies et parfois cancers', reglementation: 'Les travailleurs exposés à des agents biologiques doivent être informés et formés sur les risques pour la santé et les prescriptions en matière d\'hygiène, sur les précautions à prendre pour éviter l\'exposition, sur le port et l\'utilisation des équipements et des vêtements de protection', source: 'https://www.inrs.fr/risques/biologiques/ce-qu-il-faut-retenir.html', sectors: ["sante", "agriculture", "restauration", "assainissement", "dechets"] },
  { risque: 'Bitume', situations: 'L’exposition au bitume et à ses dérivés', consequences: 'Toux, maux de têtes ou encore troubles du sommeil', reglementation: '', source: 'https://www.inrs.fr/risques/bitume/ce-qu-il-faut-retenir.html', sectors: ["btp", "transport"] },
  { risque: 'Bruit', situations: 'Environnement bruyant, intensité sonore', consequences: 'Surdité, gêne, fatigue cognitive, stress, trouble cardio vasculaire, concentration', reglementation: 'Le cadre réglementaire de la prévention des risques liés à l’exposition au bruit est identique à celui de tout autre risque. La prévention des risques professionnels s’appuie sur une démarche dont les principes généraux sont édictés par le Code du travail (article L. 4121-2 31).', source: 'https://www.inrs.fr/risques/bruit/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "restauration", "agriculture", "transport"] },
  { risque: 'Travail à la chaleur', situations: 'Environnement marqués par des températures élevées', consequences: 'Crampes, déshydratation, épuisement, coup de chaleur, décés', reglementation: '', source: 'https://www.inrs.fr/risques/chaleur/ce-qu-il-faut-retenir.html', sectors: ["btp", "restauration", "industrie", "agriculture"] },
  { risque: 'Champs électromagnétiques', situations: 'Dès lors qu’une source d’électricité est présente dans l’environnement, des champs électriques et magnétiques sont émis.', consequences: 'Echauffement des tissus biologiques, stimulation du système nerveux, troubles visuels', reglementation: 'Le Code du travail fixe le cadre réglementaire applicable à la prévention des risques d’exposition aux champs électromagnétiques aux articles R. 4453-1 à R. 4453-34. 40', source: 'https://www.inrs.fr/risques/champs-electromagnetiques/ce-qu-il-faut-retenir.html', sectors: ["industrie", "sante"] },
  { risque: 'Risques chimiques', situations: 'Contact avec des Produits chimiques', consequences: 'Irritations des voies respiratoires, cutanées, eczémas, cancer…', reglementation: '', source: 'https://www.inrs.fr/risques/chimiques/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "agriculture", "restauration", "nettoyage", "sante"] },
  { risque: 'Chutes de plain pied', situations: 'Perte d\'équilibre, tribucher sur un obstacle,….', consequences: 'Hématomes, entorses,…', reglementation: 'Le traitement des risques de chutes de plain-pied est concerné au même titre que l’ensemble des risques professionnels par les dispositions réglementaires générales de prévention (articles L. 4121-1 à 5 du Code du travail).', source: 'https://www.inrs.fr/risques/chutes-de-plain-pied/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Chutes de hauteur', situations: 'Perte d\'équilibre.', consequences: 'Blessures diverses plus au moins graves,…', reglementation: '', source: 'https://www.inrs.fr/risques/chutes-hauteur/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "logistique", "agriculture"] },
  { risque: 'Chute d\'objet', situations: 'Instabilité d\'un objet en hauteur, attraper un objet.', consequences: 'Lésions cutanées ostéoarticulaires, plaies, luxations, fractures,…', reglementation: '', source: '', sectors: ["btp", "industrie", "logistique", "commerce"] },
  { risque: 'Ciment', situations: 'Manipulation du ciment.', consequences: 'Irritations de la peau, Eczéma allergique, Irritations oculaires, Rhinites, Pathologies broncho-pulmonaires .', reglementation: '', source: 'https://www.inrs.fr/risques/ciment/ce-qu-il-faut-retenir.html', sectors: ["btp"] },
  { risque: 'Agents chimiques CMR', situations: '', consequences: 'cancer, atteinte à la fertilité féminine et masculine,', reglementation: 'La prévention du risque d’exposition à des agents chimiques cancérogènes, mutagènes ou toxiques pour la reproduction (CMR) relève du Code du travail (articles R. 4412-59 à R. 4412-93) et s’inscrit dans la prévention du risque chimique.', source: 'https://www.inrs.fr/risques/cmr-agents-chimiques/ce-qu-il-faut-retenir.html', sectors: ["industrie", "chimie", "sante", "agriculture"] },
  { risque: 'Covid 19 et prévention en entreprise', situations: 'Contacts étroits avec une personne infectée.', consequences: 'une fièvre ou sensation de fièvre ; des signes respiratoires, comme une toux, un essoufflement ou une sensation d’oppression dans la poitrine ; le nez qui coule, un mal de gorge ; une fatigue importan', reglementation: '', source: 'https://www.inrs.fr/risques/COVID19-prevention-entreprise/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Risques liés au déplacements', situations: 'Conduite d\'un véhiule : Collisions, accidents de la route. Circulation à pied : heurt, glissade ou entorse.', consequences: 'Blessures diverses plus au moins graves,…', reglementation: '', source: 'https://www.inrs.fr/risques/deplacements/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Risques électriques', situations: 'Intensité électrique ; Contact, direct ou non, avec une pièce nue sous tension, le risque de court-circuit et le risque d’arc électrique.', consequences: 'Brûlures, Electrisation, Electrocution', reglementation: 'Pour exécuter des travaux d’ordre électrique ou non sur ou à proximité d’une installation électrique, une habilitation est obligatoire. L’employeur la délivre aux travailleurs concernés reconnus aptes par le médecin du travail dans le cadre du suivi médical renforcé et ayant reçu une form', source: 'https://www.inrs.fr/risques/electriques/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "tertiaire"] },
  { risque: 'Entreprises extérieures', situations: 'Intervention d\'une entreprise sous traitante', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/entreprises-exterieures/mesures-prevention-prealables-intervention.html', sectors: ["all"] },
  { risque: 'Envrionnement spécifique de travail', situations: 'Environnements marqués par des conditions d’ambiance particulières  : températures élevées ou au contraire très froides, pression hyperbare, altitude, espaces confinés…', consequences: 'Fatigue, sueurs, nausées, maux de tête, vertiges, crampes, déshydratation, coup de chaleur…', reglementation: '', source: 'https://www.inrs.fr/risques/environnements-specifiques-de-travail/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "agriculture"] },
  { risque: 'Exosquelettes', situations: 'Risques mécaniques, électriques, thermiques, liés au bruit et aux vibrations, etc.', consequences: 'Postures contraignantes, de stress, de fatigue cognitive (surcharge informationnelle), de troubles proprioceptifs ou encore de perte d’équilibre ou de chute', reglementation: '', source: 'https://www.inrs.fr/risques/exosquelettes/ce-qu-il-faut-retenir.html', sectors: ["industrie", "logistique"] },
  { risque: 'Epuisement professionnel ou burnout', situations: 'Surcharge de travail, pression temporelle,Faible contrôle sur son travail, faibles récompenses, manque d’équité, coflits de valeur, demandes contradictoires, manque de clarté dans les objectifs, les moyens.', consequences: 'Epuisement émotionnel, la dépersonnalisation ou le cynisme, le sentiment de non-accomplissement personnel au travail', reglementation: '', source: 'https://www.inrs.fr/risques/epuisement-burnout/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Espaces confinés', situations: 'Une atmosphère appauvrie en oxygène, toxique ou explosive', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/espaces-confines/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "assainissement", "dechets"] },
  { risque: 'Explosion sur le lieu de travail', situations: 'Manipulation des produits chimiques ou à fort empoussièrement (industrie du bois, des métaux, de l’agroalimentaire', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/explosion/ce-qu-il-faut-retenir.html', sectors: ["industrie", "chimie", "btp"] },
  { risque: 'Fabrication additive', situations: 'Manutention, aux rayonnements optiques, à l’utilisation de matériel électrique', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/fabrication-additive/ce-qu-il-faut-retenir.html', sectors: ["industrie"] },
  { risque: 'Fibres autres que l\'amiante', situations: 'Expositions à des fibres classées comme cancérogènes, mutagènes, toxiques', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/fibres-hors-amiante/ce-qu-il-faut-retenir.html', sectors: ["industrie", "btp"] },
  { risque: 'Fluide de coupe', situations: 'Usinage de pièces dans les secteurs de la métallurgie et de l’automobile, contenant des substances chimiques', consequences: 'Affections cutanées ou respiratoires', reglementation: '', source: 'https://www.inrs.fr/risques/fluides-coupe/ce-qu-il-faut-retenir.html', sectors: ["industrie"] },
  { risque: 'Formaldéhyde', situations: 'En raison de sa forte réactivité, le formaldéhyde est utilisé dans de nombreux secteurs d’activités : santé, fabrication de matériaux polymères, etc. Cette réactivité lui confère néanmoins des propriétés dangereuses', consequences: 'Inflammable, corrosif, toxique. Il peut également favoriser l’apparition de réactions allergiques et la survenue de cancer', reglementation: '', source: 'https://www.inrs.fr/risques/formaldehyde/ce-qu-il-faut-retenir.html', sectors: ["industrie", "sante"] },
  { risque: 'Fumée de soudage', situations: 'Exposition aux fumées de soudage de métaux', consequences: 'Les fumées de soudage peuvent être à l’origine d’intoxications entraînant la survenue de pathologies aiguës ou chroniques.', reglementation: '', source: 'https://www.inrs.fr/risques/fumees-soudage/ce-qu-il-faut-retenir.html', sectors: ["industrie", "btp"] },
  { risque: 'Travail au froid', situations: 'Activités réalisés dans des Entrepôts frigorifiques, chambres froides, travaux en extérieur en hiver', consequences: 'Perte de la dextérité, hypothermie, syndrome de Raynaud, TMS,…', reglementation: '', source: 'https://www.inrs.fr/risques/froid/ce-qu-il-faut-retenir.html', sectors: ["logistique", "restauration", "btp", "agriculture"] },
  { risque: 'Gaz d\'échappement', situations: 'Utilisateurs d’engins à moteurs diesel pour la réalisation de travaux souterrains, conducteurs de chariots automoteurs diesel passant un temps notoire à l’intérieur d’entrepôts… Travailleurs chargés de l’entretien ou du contrôle technique des véhicul', consequences: 'Fatigue, nausées, maux de tête, perte de connaissance, comas parfois mortels', reglementation: '', source: 'https://www.inrs.fr/risques/gaz-echappement/ce-qu-il-faut-retenir.html', sectors: ["transport", "btp", "logistique", "agriculture"] },
  { risque: 'Harcélement sexuel et agissement sexistes', situations: 'Harcèlement sexuel et les agissements sexistes au travail', consequences: 'Conséquences à long terme sur la santé physique et mentale des salariés,', reglementation: 'Depuis le 1er janvier 2019, des référents harcèlement sexuel doivent être désignés à la fois par l’employeur (obligatoire pour les entreprises de plus de 250 salariés) et par les représentants du personnel (dès qu’un CSE est présent dans l’entreprise)', source: 'https://www.inrs.fr/risques/harcelements-sexuel-agissements-sexistes/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Harcèlement moral et violence interne', situations: 'Tensions, brimades, insultes, des relations de travail qui se détériorent', consequences: 'Conséquences à long terme sur la santé mentale des salariés,', reglementation: 'La prévention du harcèlement moral et des violences internes au travail s’inscrit dans le cadre de l’obligation générale qui incombe à l’employeur d’évaluer les risques et de prendre les mesures nécessaires pour assurer la sécurité et protéger la santé physique et mentale de ses salariés', source: 'https://www.inrs.fr/risques/harcelements-violences-internes/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Heurt, glissage et autres pertubations du mouvement au travail', situations: 'L’encombrement du sol, la maladresse ou l’inattention', consequences: 'Dommages corporels plus ou moins graves en fonction de l\'évenement', reglementation: '', source: 'https://www.inrs.fr/risques/heurts-glissades-perturbations-mouvement/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Incendie sur le lieu de travail', situations: 'Elles peuvent être amenées notamment par le procédé lui-même (flammes, surfaces chaudes...), par des opérations particulières (meulage, soudage, travaux de maintenance), par l’installation électrique .', consequences: 'Brûlures plus au moins grave, inhalation de fumées toxique, asphyxie,…', reglementation: '', source: 'https://www.inrs.fr/risques/incendie-lieu-travail/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Lean Management', situations: 'Améliorer les résultats en matière de qualité, de productivité, de délais et de réduction des coûts.', consequences: 'Les troubles musculo-squelettiques, le stress ou plus largement la santé mentale.', reglementation: '', source: 'https://www.inrs.fr/risques/lean-management/ce-qu-il-faut-retenir.html', sectors: ["industrie", "logistique"] },
  { risque: 'Organisation de la maintenance', situations: 'Action de maintenance des équipements.', consequences: 'Maladies professionnelles, telles que les troubles musculo-squelettiques (TMS), les cancers professionnels ou les surdités professionnelles', reglementation: '', source: 'https://www.inrs.fr/risques/maintenance/ce-qu-il-faut-retenir.html', sectors: ["industrie", "btp", "transport"] },
  { risque: 'Mécanique', situations: 'Elément en mouvement peut entrer en contact avec une partie du corps humain (ex : écrasement, cisaillement, happement, chocs, perforation,….)', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/mecaniques/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "agriculture", "transport"] },
  { risque: 'Meopa', situations: 'inhalation du gaz', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/meopa/ce-qu-il-faut-retenir.html', sectors: ["sante"] },
  { risque: 'Nanomatériaux', situations: 'Transfert, échantillonnage, pesée ; transvasement, agitation, mélange et séchage ; usinage de nanocomposites ; conditionnement, stockage et transport des produits ; nettoyage, entretien et maintenance des équipements et des locaux.', consequences: 'Effets néfastes sur l\'appareil respiratoire, gastro-intestinal,…', reglementation: '', source: 'https://www.inrs.fr/risques/nanomateriaux/ce-qu-il-faut-retenir.html', sectors: ["industrie", "chimie"] },
  { risque: 'Organisation du travail', situations: 'Horaires,  rythme de travail, des modes de production, de la circulation des marchandises et des personnes, ou encore de la gestion des interventions d’entreprises extérieures ou des opérations de maintenance.', consequences: 'Risques psychosociaux, troubles musculosquelettiques, accidents.', reglementation: '', source: 'https://www.inrs.fr/risques/organisation/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Pertubateurs endocriniens', situations: 'Expositions peuvent être liées à l’utilisation de certaines matières premières (plastifiants, solvants…), à la fabrication ou l’utilisation de produits contenant des perturbateurs endocriniens (peintures, colles, vernis…) ou encore à la présence de d', consequences: 'Effets néfastes sur la reproduction, la croissance, le développement ou encore le métabolisme... Ces effets concernent les individus directement exposés mais également leur descendance.', reglementation: '', source: 'https://www.inrs.fr/risques/perturbateurs-endocriniens/ce-qu-il-faut-retenir.html', sectors: ["industrie", "chimie", "agriculture"] },
  { risque: 'Plomb', situations: 'Exposiition au plomb (batiment, industrie, artisanat) Le plomb peut pénétrer dans l\'organisme par le nez (poussières, fumées) ou la bouche (mains sales, aliments souillés).', consequences: 'Système nerveux : troubles de l\'humeur et de la mémoire, détérioration des capacités intellectuelles, atteinte des nerfs moteurs périphériques ; au niveau des reins : perturbation des fonctions d\'élim', reglementation: '', source: 'https://www.inrs.fr/risques/plomb/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie"] },
  { risque: 'Polyexpositions', situations: 'Etre exposés en même temps à des nuisances multiples. Ces nuisances peuvent être chimiques, biologiques, physiques (bruit, vibrations, rayonnement…) ou liées à l’activité physique, auxquelles s’ajoutent l’influence des facteurs organisationnels et ps', consequences: '', reglementation: '', source: 'https://www.inrs.fr/risques/polyexpositions/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "agriculture"] },
  { risque: 'Poussières', situations: 'Inalhasion des poussières, les poussières peuvent être produites par de multiples procédés : broyage de minéraux, manipulation de produits pulvérulents comme la farine ou le sucre, usinage du bois ou d’autres matériaux…', consequences: 'Irritations des voies respiratoires, cutanées, eczémas, cancer…', reglementation: '', source: 'https://www.inrs.fr/risques/poussieres/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "agriculture"] },
  { risque: 'Poussières de bois', situations: 'Inalhasion des poussières  (ex: usinage du bois)', consequences: 'Irritations des voies respiratoires, cutanées, eczémas, cancer…', reglementation: '', source: 'https://www.inrs.fr/risques/poussieres-bois/ce-qu-il-faut-retenir.html', sectors: ["industrie", "btp"] },
  { risque: 'Risques psychosociaux (RPS)', situations: 'Intensité et temps de travail, exigences émotionnelles, autonomie, rapports sociaux au travail, conflit de valeurs / sens du travail, insécurité de la situation de travail,…', consequences: 'Troubles Psychosociaux (ex: Dépression, anxiété, TMS, maladies cardiovasculaires, troubles du sommeil, angoisse, sensation de mal-être, perturbations de la concentration, douleurs, coliques, maux de t', reglementation: '', source: 'https://www.inrs.fr/risques/psychosociaux/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Radon en milieu de travail', situations: 'Inalhasion de gaz radioactif naturel qui est émis par les sols en concentration plus ou moins importante en fonction de la nature des roches (surtout granitiques, volcaniques, et certains schistes)', consequences: 'Cancers broncho-pulmonaires', reglementation: '', source: 'https://www.inrs.fr/risques/radon/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie"] },
  { risque: 'Rayonnement ionisants', situations: 'L’exposition à ces rayonnements peut être interne (ingestion, inhalation de substances radioactives, passage percutané) et/ou externe (source à distance ou au contact).', consequences: 'Lésions cellulaires, brûlures, nausées, cancers, leucémies, cataracte, destructions cellulaires à forte dose,…', reglementation: '', source: 'https://www.inrs.fr/risques/rayonnements-ionisants/ce-qu-il-faut-retenir.html', sectors: ["sante", "industrie"] },
  { risque: 'Rayonnements optiques', situations: 'L\'exposition prolongée à des rayonnements optiques de forte intensité . On utilise les propriétés du rayonnement ultraviolet dans l\'industrie pour le séchage des encres, la polymérisation des colles, la détection de défauts, la stérilisation (traitem', consequences: 'Les atteintes de la peau : coup de soleil, de vieillissement de la peau et de cancer. Pour l\'œil : des lésions de la cornée, de la conjonctive, voire de la rétine. A long terme l\'exposition chronique', reglementation: '', source: 'https://www.inrs.fr/risques/rayonnements-optiques/ce-qu-il-faut-retenir.html', sectors: ["industrie", "sante"] },
  { risque: 'Risques routiers', situations: 'Conduire pour se rendre au travail et en revenir ou déplacements professionnels.', consequences: 'Blessures diverses plus au moins graves,… chocs, conséquences bénignes, Lésions cérébrales, des membres inférieurs, hémorragie interne,...', reglementation: 'L’article L. 4121-1 31 du Code du travail fait obligation à l’employeur d’assurer la sécurité de ses salariés. Les principes généraux de prévention énumérés dans le Code du travail, doivent servir de guide à l’employeur pour atteindre cet objectif. L’article L. 4121-3 32 précise que la mise en en œu', source: 'https://www.inrs.fr/risques/routiers/ce-qu-il-faut-retenir.html', sectors: ["transport", "btp", "commerce", "logistique"] },
  { risque: 'Silice cristalline', situations: 'Les travaux susceptibles d’exposer les salariés à l’inhalation de poussières de silice cristalline sont présents dans la majorité des industries de manufacture et de construction.La voie de pénétration de la silice cristalline dans l’organisme est la', consequences: 'Une irritation des yeux et des voies respiratoires, des bronchites chroniques et une fibrose pulmonaire irréversible nommée silicose.', reglementation: '', source: 'https://www.inrs.fr/risques/silice-cristalline/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie"] },
  { risque: 'Solvants', situations: 'Peinture, nettoyage des métaux ou des textiles, décapage, fabrication des parfums… Les solvants peuvent pénétrer dans l\'organisme par trois voies : la voie respiratoire (grâce à leur volatilité) ; la voie cutanée (quel que soit l\'état de la peau) ; l', consequences: 'Exposition à une forte dose : une intoxication aiguë. Une exposition régulière et même à faible dose, à un ou plusieurs solvants : peut entraîner à plus ou moins long terme une atteinte souvent irréve', reglementation: '', source: 'https://www.inrs.fr/risques/solvants/ce-qu-il-faut-retenir.html', sectors: ["industrie", "btp", "nettoyage"] },
  { risque: 'Stress au travail', situations: 'On parle de stress au travail quand une personne ressent un déséquilibre entre ce qu’on lui demande de faire dans le cadre professionnel et les ressources dont elle dispose pour y répondre. La surcharge de travail, des objectifs insuffisamment défini', consequences: 'Les effets sont plus ou moins grave, pouvant générer un burnout.', reglementation: '', source: 'https://www.inrs.fr/risques/stress/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Suicide', situations: '', consequences: 'Les effets sont plus ou moins grave, pouvant pouvant entrainer la mort', reglementation: '', source: 'https://www.inrs.fr/risques/suicide-travail/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Télétravail', situations: 'Des postes de travail informatique mal aménagés ;  Postures sédentaires prolongées ; l’usage intensif de l’écran d’ordinateur ; une organisation du travail non adaptée.', consequences: 'Un aménagement non adapté du poste de travail informatique à domicile peut générer des contraintes posturales au niveau des membres. pathologies cardiovasculaires (hypertension artérielle, insuff', reglementation: '', source: 'https://www.inrs.fr/risques/teletravail/ce-qu-il-faut-retenir.html', sectors: ["tertiaire", "bureau"] },
  { risque: 'Troubles musculosquelettiques (TMS)', situations: 'Ils sont le résultat de la combinaison de multiples causes liées au poste de travail et à son environnement, à l\'organisation du travail, au climat social dans l\'entreprise. L’accroissement des contraintes de productivité, l’intensification du t', consequences: 'Les TMS sont des maladies qui touchent les tissus mous péri-articulaires des membres supérieurs et inférieurs. Ils affectent les muscles, les tendons, les ligaments, les nerfs, mais aussi les vaissea', reglementation: 'Il convient de se reporter, en premier lieu, à l’obligation générale qui incombe à l’employeur de préserver la santé physique et mentale de ses salariés (article L. 4121-1 du Code du travail). Il en découle qu’il devra prendre les mesures de prévention nécessaires pour éviter toute maladi', source: 'https://www.inrs.fr/risques/tms-troubles-musculosquelettiques/ce-qu-il-faut-retenir.html', sectors: ["all"] },
  { risque: 'Travail sur écran', situations: 'Les facteurs de risque sont de nature biomécanique (posture statique prolongée et contraignante, répétitivité des gestes…), physiologique (faible dépense énergétique), organisationnelle (durée journalière, travail intensif, absence de pause, contenu', consequences: 'Le travail sur écran peut engendrer des effets sur la santé tels que des troubles musculosquelettiques, de la fatigue visuelle, du stress et d’autres effets liés aux postures sédentaires (troubles mét', reglementation: '', source: 'https://www.inrs.fr/risques/travail-ecran/ce-qu-il-faut-retenir.html', sectors: ["tertiaire", "bureau", "commerce"] },
  { risque: 'Travail en horaires atypiques', situations: 'Le travail de nuit, les ruthmes de travail irréguliers ou cycliques, travail le soir, travail le weekend, journée fragmentée, astreintes,…', consequences: 'Troubles du sommeil, fatigue, troubles digestifs, déséquilibre nutritionnel, trouble de l\'humeur, surpoids, hypertension artérielle,…', reglementation: '', source: 'https://www.inrs.fr/risques/travail-horaires-atypiques/ce-qu-il-faut-retenir.html', sectors: ["sante", "restauration", "transport", "industrie", "commerce"] },
  { risque: 'Travail isolé', situations: 'Réaliser seul une tâche dans un environnement de travail où l’on ne peut être vu ou entendu directement par d’autres personnes, et où la probabilité de visite est faible.', consequences: 'L’isolement peut être à la fois physique et psychique, mais en cas d’accident, l’absence d’assistance fait qu’il est dans tous les cas un facteur d’aggravation des dommages pour le salarié.', reglementation: '', source: 'https://www.inrs.fr/risques/travail-isole/ce-qu-il-faut-retenir.html', sectors: ["btp", "transport", "agriculture", "sante"] },
  { risque: 'Vibrations transmises à l\'ensemble du corps', situations: 'La conduite régulière d’un véhicule ou d’un engin de chantier, de transport ou de manutention', consequences: 'Douleurs lombaires, hernies discales, lombalgie, nausées…', reglementation: '', source: 'https://www.inrs.fr/risques/vibration-corps-entier/ce-qu-il-faut-retenir.html', sectors: ["btp", "transport", "agriculture", "industrie"] },
  { risque: 'Vibrations transmises aux membres supérieurs', situations: 'Les vibrations générées par certaines machines portatives ou guidées à la main.', consequences: 'Perte de la dextérité manuelle, maladie de Raynaud, TMS, diminution de la force musculaire,...', reglementation: '', source: 'https://www.inrs.fr/risques/vibration-membres-superieurs/ce-qu-il-faut-retenir.html', sectors: ["btp", "industrie", "agriculture"] },
  { risque: 'Zoonoses', situations: 'Contact entre l’animal et l’homme. Les agents biologiques responsables de zoonoses peuvent être des bactéries, des virus, des parasites, ou des prions. Certains champignons microscopiques peuvent également être transmis par des animaux.  Les activité', consequences: 'Maladies infectieuses, champignons microscopiques', reglementation: '', source: 'https://www.inrs.fr/risques/zoonoses/ce-qu-il-faut-retenir.html', sectors: ["agriculture", "sante"] },
]

// Mapping des templates secteur vers les tags INRS
export const SECTOR_TO_TAGS = {
  'btp': ['btp'],
  'transport': ['transport'],
  'commerce': ['commerce'],
  'restauration': ['restauration'],
  'industrie': ['industrie'],
  'sante': ['sante'],
  'agriculture': ['agriculture'],
  'tertiaire': ['tertiaire', 'bureau'],
  'bureau': ['tertiaire', 'bureau'],
  'nettoyage': ['nettoyage'],
  'logistique': ['logistique'],
  'assainissement': ['assainissement', 'btp'],
  'dechets': ['dechets'],
  'chimie': ['chimie', 'industrie'],
  'accueil': ['accueil', 'commerce'],
}

export function getInrsRisksForSector(sectorTemplate) {
  if (!sectorTemplate) return INRS_RISKS
  const sectors = sectorTemplate.split(',').map(s => s.trim())
  const tags = new Set()
  sectors.forEach(s => {
    const mapped = SECTOR_TO_TAGS[s]
    if (mapped) mapped.forEach(t => tags.add(t))
    else tags.add(s)
  })
  return INRS_RISKS.filter(r => r.sectors.includes('all') || r.sectors.some(s => tags.has(s)))
}

// Formations sécurité pré-remplies Access Formation
export const FORMATIONS_SECURITE = [
  { formation: 'SST - Sauveteur Secouriste du Travail', reglementation: 'Art. R4224-15 du Code du Travail', periodicite: 'Recyclage 24 mois - Min. 1 SST dans chaque atelier' },
  { formation: 'Equipier de Premiere Intervention (EPI incendie)', reglementation: 'Art. R4227-28 et R4227-39 du Code du Travail', periodicite: 'Min. 1 personne formee presente durant les heures de travail' },
  { formation: 'Evacuation des batiments', reglementation: 'Art. R4227-39 du Code du Travail', periodicite: 'Exercice d\'evacuation tous les 6 mois' },
  { formation: 'CACES R482 - Engins de chantier', reglementation: 'Art. R4323-55 du Code du Travail', periodicite: 'Recyclage 5 ans + autorisation de conduite employeur' },
  { formation: 'CACES R489 - Chariots automoteurs', reglementation: 'Art. R4323-55 du Code du Travail', periodicite: 'Recyclage 5 ans + autorisation de conduite employeur' },
  { formation: 'CACES R486 - Nacelles (PEMP)', reglementation: 'Art. R4323-55 du Code du Travail', periodicite: 'Recyclage 5 ans + autorisation de conduite employeur' },
  { formation: 'Habilitation electrique', reglementation: 'Art. R4544-10 du Code du Travail', periodicite: 'Recyclage 3 ans' },
  { formation: 'AIPR - Intervention Proximite Reseaux', reglementation: 'Decret 2011-1241 et arrete du 22 dec 2015', periodicite: 'Recyclage 5 ans - Obligatoire pour travaux a proximite de reseaux' },
  { formation: 'Travail en hauteur / Port du harnais', reglementation: 'Art. R4323-89 du Code du Travail', periodicite: 'Recyclage recommande tous les 3 ans' },
  { formation: 'CATEC - Espaces confines', reglementation: 'Recommandation R472 CNAM', periodicite: 'Recyclage 3 ans - Obligatoire pour interventions en espace confine' },
  { formation: 'Gestes et postures / PRAP', reglementation: 'Art. R4541-4 et R4541-8 du Code du Travail', periodicite: 'Recyclage 24 mois (PRAP)' },
  { formation: 'Membres du CSE (entreprise >= 11 sal.)', reglementation: 'Art. R2315-10 du Code du Travail', periodicite: 'A chaque election de nouveaux membres' },
]
